name: Cypress Continuous Integration Tests

on: 
  pull_request:
    branches:
        - main
        - develop

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest

    container: 
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.116-1-ff-132.0.1-edge-130.0.2849.68-1
      options: --user 1001

    strategy:
      matrix:
        project: [web-tests] # Defines which project will be tested

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Instalar dependências do projeto
        run: yarn install

      - name: Criar arquivo .env
        run: cp .env.example .env

      - name: Executar migrations Prisma
        run: npx prisma migrate dev

      - name: Iniciar servidor em segundo plano
        run: yarn dev &

      - name: Aguardar o servidor na porta 3010
        run: npx wait-on http://localhost:3010

      - name: Executar testes Cypress (headless)
        working-directory: ${{ matrix.project }}
        run: |
          echo "Rodando Cypress no projeto ${{ matrix.project }}"
          npx cypress run --browser chrome --headless

